application:
  bindAddress: :8453
  production: false
  debug: false
database:
  address: localhost:3403
  name: event
  username: bitfever
  password: bitfever
authentication:
  authority: https://bitfever-server:8443/auth/realms/bitfever
messaging:
  address: localhost:8450
  username: rabbit-admin
  password: rabbit.admin
